//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUIPRT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MUIPRT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backd {
            get {
                object obj = ResourceManager.GetObject("backd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap backhov {
            get {
                object obj = ResourceManager.GetObject("backhov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fwd {
            get {
                object obj = ResourceManager.GetObject("fwd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fwdd {
            get {
                object obj = ResourceManager.GetObject("fwdd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fwdhov {
            get {
                object obj = ResourceManager.GetObject("fwdhov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap go {
            get {
                object obj = ResourceManager.GetObject("go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap god {
            get {
                object obj = ResourceManager.GetObject("god", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap gohov {
            get {
                object obj = ResourceManager.GetObject("gohov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HEADER {
            get {
                object obj = ResourceManager.GetObject("HEADER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ico {
            get {
                object obj = ResourceManager.GetObject("ico", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap re {
            get {
                object obj = ResourceManager.GetObject("re", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refd {
            get {
                object obj = ResourceManager.GetObject("refd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap refhov {
            get {
                object obj = ResourceManager.GetObject("refhov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stopd {
            get {
                object obj = ResourceManager.GetObject("stopd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stophov {
            get {
                object obj = ResourceManager.GetObject("stophov", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Text_0 {
            get {
                return ResourceManager.GetString("Text_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.. .
        /// </summary>
        public static string Text_Done {
            get {
                return ResourceManager.GetString("Text_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Loading....
        /// </summary>
        public static string Text_Done_Loading {
            get {
                return ResourceManager.GetString("Text_Done_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading page. Check proxy settings or URL..
        /// </summary>
        public static string Text_Error_loading {
            get {
                return ResourceManager.GetString("Text_Error_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string Text_Finished {
            get {
                return ResourceManager.GetString("Text_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved... .
        /// </summary>
        public static string Text_Moved {
            get {
                return ResourceManager.GetString("Text_Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxies.
        /// </summary>
        public static string Text_Proxies {
            get {
                return ResourceManager.GetString("Text_Proxies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting....
        /// </summary>
        public static string Text_Redirecting {
            get {
                return ResourceManager.GetString("Text_Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral.
        /// </summary>
        public static string Text_Referral {
            get {
                return ResourceManager.GetString("Text_Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrer.
        /// </summary>
        public static string Text_Referrer {
            get {
                return ResourceManager.GetString("Text_Referrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Text_Running {
            get {
                return ResourceManager.GetString("Text_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped..
        /// </summary>
        public static string Text_Stopped {
            get {
                return ResourceManager.GetString("Text_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt*)|*.txt*.
        /// </summary>
        public static string Text_Text_Files {
            get {
                return ResourceManager.GetString("Text_Text_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs.
        /// </summary>
        public static string Text_Urls {
            get {
                return ResourceManager.GetString("Text_Urls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URLs to be viewed.
        /// </summary>
        public static string Text_Urls_to_be_viewed {
            get {
                return ResourceManager.GetString("Text_Urls_to_be_viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agents.
        /// </summary>
        public static string Text_User_Agents {
            get {
                return ResourceManager.GetString("Text_User_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useragents to use.
        /// </summary>
        public static string Text_Useragents_to_use {
            get {
                return ResourceManager.GetString("Text_Useragents_to_use", resourceCulture);
            }
        }
    }
}
